Add missing required `error` argument to `IndicoRequestError()`
This fixes a bug where 5XX response status codes raise `TypeError:
IndicoRequestError.__init__() missing 1 required positional argument:
'error'` instead of an instance of `IndicoRequestError`.

Also includes the response content bytes as extras to aid debugging.